language: node_js
before_install:
- echo "Before install stage"
- npm install -g typescript bower
install:
- echo "Install stage"
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- make
after_success:
- bower info bluenet
- bower install bluenet
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
on:
all_branches: true
